MODEL_NAME = 'xlm-roberta-base'

RANDOM_SEED = None
NUM_OF_CLASSES = 3
MAX_LENGTH = 150
TO_USE_TAIL_TOKEN_OUTPUT = True
NUM_HIDDEN_STATES_TO_USE = 4
RAITO_OF_EVAL_DATA = 0.2

MAX_EPOCH = 5
TRAIN_BATCH_SIZE = 8
EVAL_BATCH_SIZE = 8
TEST_BATCH_SIZE = 8

LEARNING_RATE = 8e-6
LEARNING_RATE_COEFFICIENT = 40
WEIGHT_DECAY = 0.001
DROPOUT_RATE = 0.25
TO_USE_CLIP_GRAD = True